orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run YARN tests
  deploy:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'SHA256:sGOVcs+64ocW+t6g4pWx1hiEOADGSn9yw2fmXqW1dZ4'
      - checkout
      - run: yarn
      - run: yarn deploy-storybook

workflows:
  test_and_deploy:
    jobs:
      - test
          filters:
            branches:
              ignore: 'gh-pages'
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - test
