orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run YARN tests
  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - run: yarn
      - run: yarn deploy-storybook

workflows:
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
