orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  test:
    executor: my-ubuntu-exec
    steps:
      - checkout
      - run: yarn
      - run: yarn test

workflows:
  build_and_test:
    jobs:
      - test
