orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run YARN tests
  deploy:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'a3:71:9a:77:b4:ae:e4:26:72:94:70:bc:49:5d:c0:21'
      - checkout
      - run: yarn
      - run: yarn deploy-storybook

workflows:
  test_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: 'gh-pages'
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - test
