orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
      - checkout
      - run: yarn
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - run: yarn
      - run: yarn deploy-storybook

workflows:
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
