export const flexibleBoxClasses: { [key in FlexibleBoxClasses]: string } = {
  alignItemsStart: 'align-items-start',
  alignItemsEnd: 'align-items-end',
  alignItemsCenter: 'align-items-center',
  alignItemsBaseline: 'align-items-baseline',
  alignItemsStretch: 'align-items-stretch',
  justifyContentStart: 'justify-content-start',
  justifyContentEnd: 'justify-content-end',
  justifyContentCenter: 'justify-content-center',
  justifyContentSpaceAround: 'justify-content-space-around',
  justifyContentSpaceEvenly: 'justify-content-space-evenly',
  justifyContentSpaceBetween: 'justify-content-space-between',
  alignContentStart: 'align-content-start',
  alignContentEnd: 'align-content-end',
  alignContentCenter: 'align-content-center',
  alignContentSpaceAround: 'align-content-space-around',
  alignContentSpaceEvenly: 'align-content-space-evenly',
  alignContentSpaceBetween: 'align-content-space-between',
  alignContentBaseline: 'align-content-baseline',
  alignContentStretch: 'align-content-stretch',
  alignSelfStart: 'align-self-start',
  alignSelfEnd: 'align-self-end',
  alignSelfCenter: 'align-self-center',
  alignSelfBaseline: 'align-self-baseline',
  alignSelfStretch: 'align-self-stretch',
  alignSelfAuto: 'align-self-auto',
  column: 'flexible-box-column',
  row: 'flexible-box-row',
  columnReverse: 'flexible-box-column-reverse',
  rowReverse: 'flexible-box-row-reverse',
  flex: 'flexible-box-flex',
  inlineFlex: 'flexible-box-inline-flex',
  wrap: 'flexible-box-wrap',
  noWrap: 'flexible-box-no-wrap',
  wrapReverse: 'flexible-box-wrap-reverse',
}

export type FlexibleBoxClasses =
  | 'alignItemsStart'
  | 'alignItemsEnd'
  | 'alignItemsCenter'
  | 'alignItemsBaseline'
  | 'alignItemsStretch'
  | 'justifyContentStart'
  | 'justifyContentEnd'
  | 'justifyContentCenter'
  | 'justifyContentSpaceAround'
  | 'justifyContentSpaceEvenly'
  | 'justifyContentSpaceBetween'
  | 'alignContentStart'
  | 'alignContentEnd'
  | 'alignContentCenter'
  | 'alignContentSpaceAround'
  | 'alignContentSpaceEvenly'
  | 'alignContentSpaceBetween'
  | 'alignContentBaseline'
  | 'alignContentStretch'
  | 'alignSelfStart'
  | 'alignSelfEnd'
  | 'alignSelfCenter'
  | 'alignSelfBaseline'
  | 'alignSelfStretch'
  | 'alignSelfAuto'
  | 'column'
  | 'row'
  | 'columnReverse'
  | 'rowReverse'
  | 'wrap'
  | 'noWrap'
  | 'wrapReverse'
  | 'flex'
  | 'inlineFlex'
